### ISSUE TITLE
Milestone 3 Checklist

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#151]
Here is the checklist with things to do before the 3rd milestone 4/1/2019:

- [x] Ensure package can run from metadata
- [x] tag v0.2.0 release and push to metadata
- [x] update readme
- [x] ensure that examples work
- [x] ensure docker container works
- [x] identify docs pages/paragraphs that need to be updated 
- [x] update docs pages
- [x] clear out issues
- [x] send PDF of progress.md to aske@darpa.mil

If you think of anything else comment below.

**Comment by jpfairbanks** [comment]
We have to update and test our docker container.

**Comment by jpfairbanks** [comment]
- [ ] fix docstrings on modeltools/#ModelTools-Library-Reference-1

**Comment by jpfairbanks** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/22571
